export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero/Hero";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as ProjectCard } from "./ProjectCard";
export { default as Experience } from "./Experience";
export { default as Skills } from "./Skills";
export { default as Projects } from "./Projects";
export { default as Footer } from "./Footer";
export { heroData } from "./Hero/HeroData";
export { default as DemoNavbar } from "./DemoNavbar";
export type { heroDataType } from "./Hero/HeroData";
export { default as CloseDoorNavbar } from "./CloseDoorNavbar";
export { default as Header } from "./Header";
export { default as Certifications } from "./Certifications";
export { default as Education } from "./Education";
